name: 编译苹果版本 APP (arm64)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build Qt for macOS arm64
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install py7zr in isolated environment
        run: |
          python -m pip install --upgrade pip
          python -m pip install py7zr==0.20.*

      - name: Install Qt (with charts & multimedia)
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.1'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
          modules: 'qtcharts qtmultimedia'

      - name: Build project for arm64
        run: |
          echo "QMAKE_APPLE_DEVICE_ARCHS = arm64" >> arm64.conf
          qmake yunying.pro QMAKE_EXTRA_CONF=arm64.conf
          make -j$(sysctl -n hw.logicalcpu)

      - name: List all .app bundles and binaries
        run: |
          find . -name "*.app" -print
          find . -type f -perm +111

      - name: Deploy .app with macdeployqt (if exists)
        run: |
          APP_PATH=$(find . -maxdepth 1 -name "yunying.app" | head -n 1)
          if [ -d "$APP_PATH" ]; then
            /Users/runner/work/${{ github.repository }}/Qt/6.6.1/macos/bin/macdeployqt "$APP_PATH"
          else
            echo "yunying.app not found, skip macdeployqt"
          fi

      - name: Upload Artifact (.app)
        uses: actions/upload-artifact@v4
        with:
          name: yunying-macos-arm64
          path: yunying.app
          if-no-files-found: warn
