name: 编译苹果版本 APP (arm64)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: 编译苹果版本 APP (arm64)
    runs-on: macos-14

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装 py7zr
        run: |
          python -m pip install --upgrade pip
          python -m pip install py7zr==0.20.*

      - name: 安装 Qt（Charts + Multimedia）
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.1'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
          modules: 'qtcharts qtmultimedia'

      - name: 构建 arm64 项目
        run: |
          echo "QMAKE_APPLE_DEVICE_ARCHS = arm64" >> arm64.conf
          qmake yunying.pro QMAKE_EXTRA_CONF=arm64.conf
          make -j$(sysctl -n hw.logicalcpu)

      - name: 列出 .app 捆绑包
        run: find . -name "*.app" -print

      - name: 打包 .app（macdeployqt）
        run: |
          if [ -d "yunying.app" ]; then
            /Users/runner/work/${{ github.repository }}/Qt/6.6.1/macos/bin/macdeployqt yunying.app
          else
            echo "yunying.app not found"
            exit 1
          fi

      - name: 压缩 yunying.app 为 7z
        run: |
          python -m py7zr compress yunying.app yunying-macos-arm64.7z

      - name: 上传 7z 压缩包
        uses: actions/upload-artifact@v4
        with:
          name: yunying-macos-arm64
          path: yunying-macos-arm64.7z
          if-no-files-found: error
