name: 编译苹果版本 APP (arm64)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: macOS arm64 编译
    runs-on: macos-14

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装 Qt（带图表和多媒体）
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.1'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
          modules: 'qtcharts qtmultimedia'

      - name: 构建 arm64 项目
        run: |
          echo "QMAKE_APPLE_DEVICE_ARCHS = arm64" >> arm64.conf
          qmake yunying.pro QMAKE_EXTRA_CONF=arm64.conf
          make -j$(sysctl -n hw.logicalcpu)

      - name: 列出所有文件和目录
        run: ls -lR

      - name: 查找 .app 产物
        run: find . -name "*.app" -print

      - name: (可选) 用 macdeployqt 打包
        run: |
          APP_PATH=$(find . -name "yuny.app" | head -n 1)
          if [ -d "$APP_PATH" ]; then
            /Users/runner/work/${{ github.repository }}/Qt/6.6.1/macos/bin/macdeployqt "$APP_PATH"
          else
            echo "yuny.app not found, skip macdeployqt"
          fi

      - name: 压缩 yuny.app
        run: |
          APP_PATH=$(find . -name "yuny.app" | head -n 1)
          if [ -d "$APP_PATH" ]; then
            zip -r yunying-macos-arm64.zip "$APP_PATH"
          else
            echo "yuny.app not found"
            exit 1
          fi

      - name: 上传压缩包
        uses: actions/upload-artifact@v4
        with:
          name: yunying-macos-arm64
          path: yunying-macos-arm64.zip
          if-no-files-found: error
