name: 编译苹果版本 APP (arm64)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: 编译苹果版本 APP (arm64)
    runs-on: macos-14

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装 py7zr in isolated environment
        run: |
          python -m pip install --upgrade pip
          python -m pip install py7zr==0.20.*

      - name: 安装Qt（带图表和多媒体）
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.1'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
          modules: 'qtcharts qtmultimedia'

      - name: 构建 arm64 项目
        run: |
          echo "QMAKE_APPLE_DEVICE_ARCHS = arm64" >> arm64.conf
          qmake yunying.pro QMAKE_EXTRA_CONF=arm64.conf
          make -j$(sysctl -n hw.logicalcpu)

      - name: 列出所有.app捆绑包和二进制文件
        run: |
          find . -name "*.app" -print
          find . -type f -perm +111

      - name: 使用macdeployqt部署.app（如果存在）
        run: |
          APP_PATH=$(find . -maxdepth 1 -name "yunying.app" | head -n 1)
          if [ -d "$APP_PATH" ]; then
            /Users/runner/work/${{ github.repository }}/Qt/6.6.1/macos/bin/macdeployqt "$APP_PATH"
          else
            echo "yunying.app not found, skip macdeployqt"
          fi

      - name: 上传人工制品（.app）
        uses: actions/upload-artifact@v4
        with:
          name: yunying-macos-arm64
          path: yunying.app
          if-no-files-found: warn
